import { useState, useEffect } from 'react'
import api from '../lib/api'
import { CalendarDays, CheckCircle2, Circle, AlertCircle, Loader2 } from 'lucide-react'

const CATEGORY_COLOR = {
  scouting:    'bg-blue-100 text-blue-700',
  fertilizing: 'bg-green-100 text-green-700',
  watering:    'bg-cyan-100 text-cyan-700',
  planting:    'bg-forest/10 text-forest',
  harvesting:  'bg-earth/10 text-earth',
  spraying:    'bg-purple-100 text-purple-700',
}

export default function Timeline() {
  const [events, setEvents]   = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.get('/api/timeline/')
      .then(r => setEvents(r.data))
      .catch(() => setEvents([]))
      .finally(() => setLoading(false))
  }, [])

  const toggle = async (event) => {
    setEvents(ev => ev.map(e => e.id === event.id ? { ...e, completed: !e.completed } : e))
    await api.patch(`/api/timeline/${event.id}/complete`).catch(() => {})
  }

  const grouped = events.reduce((acc, e) => {
    const key = e.date; (acc[key] = acc[key] || []).push(e); return acc
  }, {})

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2 mb-0.5">
          <CalendarDays size={20} className="text-forest" />
          <h1 className="font-display text-2xl text-charcoal">Farm Timeline</h1>
        </div>
        <p className="text-gray-500 text-sm">Your advisory schedule — generated by CropMind.</p>
      </div>

      {loading && (
        <div className="flex justify-center py-12">
          <Loader2 size={24} className="animate-spin text-forest" />
        </div>
      )}

      {!loading && events.length === 0 && (
        <div className="card text-center py-10">
          <CalendarDays size={28} className="text-gray-300 mx-auto mb-2" />
          <p className="text-gray-500 text-sm">No events yet. Start diagnosing crops to generate your schedule.</p>
        </div>
      )}

      {Object.entries(grouped).sort(([a], [b]) => a.localeCompare(b)).map(([date, dayEvents]) => (
        <div key={date}>
          <div className="flex items-center gap-2 mb-2">
            <div className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
              {new Date(date).toLocaleDateString('en-KE', { weekday: 'long', day: 'numeric', month: 'long' })}
            </div>
            <div className="flex-1 h-px bg-gray-100" />
          </div>
          <div className="space-y-2">
            {dayEvents.map(event => (
              <div key={event.id}
                className={`card flex items-start gap-3 cursor-pointer transition-all hover:shadow-hover
                  ${event.completed ? 'opacity-50' : ''}`}
                onClick={() => toggle(event)}>
                <div className="mt-0.5 shrink-0">
                  {event.completed
                    ? <CheckCircle2 size={20} className="text-ok" />
                    : event.urgent
                    ? <AlertCircle size={20} className="text-alert" />
                    : <Circle size={20} className="text-gray-300" />}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className={`text-sm font-semibold ${event.completed ? 'line-through text-gray-400' : 'text-charcoal'}`}>
                      {event.title}
                    </p>
                    {event.urgent && !event.completed && <span className="badge-urgent">Urgent</span>}
                  </div>
                  <p className="text-xs text-gray-500 mt-0.5">{event.description}</p>
                  <div className="flex gap-2 mt-1.5">
                    {event.crop && (
                      <span className="text-xs bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full">{event.crop}</span>
                    )}
                    <span className={`text-xs px-2 py-0.5 rounded-full ${CATEGORY_COLOR[event.category] || 'bg-gray-100 text-gray-500'}`}>
                      {event.category}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  )
}
